api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    title: MONEY TRANSFER API PLATFORM
    patch_formats:
        json:   ['application/json']
        jsonld: ['application/ld+js']
    swagger:
        versions: [3]
        api_keys:
            apiKeys:
                name: X-AUTH-TOKEN
                type: header

    collection:
        pagination:
            items_per_page: 5
            client_items_per_page: true

    eager_loading:

        enabled: true

        fetch_partial: false

        max_joins: 30
